// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.3
// source: proto/looper.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Looper_Ping_FullMethodName            = "/looper.v1.Looper/Ping"
	Looper_Shutdown_FullMethodName        = "/looper.v1.Looper/Shutdown"
	Looper_StartLoop_FullMethodName       = "/looper.v1.Looper/StartLoop"
	Looper_StopLoop_FullMethodName        = "/looper.v1.Looper/StopLoop"
	Looper_ListRuns_FullMethodName        = "/looper.v1.Looper/ListRuns"
	Looper_StreamState_FullMethodName     = "/looper.v1.Looper/StreamState"
	Looper_RespondDecision_FullMethodName = "/looper.v1.Looper/RespondDecision"
)

// LooperClient is the client API for Looper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Looper is the daemon control service spoken over the local Unix socket.
type LooperClient interface {
	// Ping checks liveness and returns the daemon version.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Shutdown asks the daemon to stop gracefully.
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	// StartLoop starts running a loop in the daemon and returns its run id.
	StartLoop(ctx context.Context, in *StartLoopRequest, opts ...grpc.CallOption) (*StartLoopResponse, error)
	// StopLoop stops a running loop.
	StopLoop(ctx context.Context, in *StopLoopRequest, opts ...grpc.CallOption) (*StopLoopResponse, error)
	// ListRuns returns the current runs known to the daemon.
	ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error)
	// StreamState streams state updates for a run (or all runs if run_id empty).
	StreamState(ctx context.Context, in *StreamStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StateUpdate], error)
	// RespondDecision answers a pending decision request (manual step, failure).
	RespondDecision(ctx context.Context, in *RespondDecisionRequest, opts ...grpc.CallOption) (*RespondDecisionResponse, error)
}

type looperClient struct {
	cc grpc.ClientConnInterface
}

func NewLooperClient(cc grpc.ClientConnInterface) LooperClient {
	return &looperClient{cc}
}

func (c *looperClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, Looper_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *looperClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, Looper_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *looperClient) StartLoop(ctx context.Context, in *StartLoopRequest, opts ...grpc.CallOption) (*StartLoopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartLoopResponse)
	err := c.cc.Invoke(ctx, Looper_StartLoop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *looperClient) StopLoop(ctx context.Context, in *StopLoopRequest, opts ...grpc.CallOption) (*StopLoopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopLoopResponse)
	err := c.cc.Invoke(ctx, Looper_StopLoop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *looperClient) ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRunsResponse)
	err := c.cc.Invoke(ctx, Looper_ListRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *looperClient) StreamState(ctx context.Context, in *StreamStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StateUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Looper_ServiceDesc.Streams[0], Looper_StreamState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamStateRequest, StateUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Looper_StreamStateClient = grpc.ServerStreamingClient[StateUpdate]

func (c *looperClient) RespondDecision(ctx context.Context, in *RespondDecisionRequest, opts ...grpc.CallOption) (*RespondDecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespondDecisionResponse)
	err := c.cc.Invoke(ctx, Looper_RespondDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LooperServer is the server API for Looper service.
// All implementations must embed UnimplementedLooperServer
// for forward compatibility.
//
// Looper is the daemon control service spoken over the local Unix socket.
type LooperServer interface {
	// Ping checks liveness and returns the daemon version.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Shutdown asks the daemon to stop gracefully.
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	// StartLoop starts running a loop in the daemon and returns its run id.
	StartLoop(context.Context, *StartLoopRequest) (*StartLoopResponse, error)
	// StopLoop stops a running loop.
	StopLoop(context.Context, *StopLoopRequest) (*StopLoopResponse, error)
	// ListRuns returns the current runs known to the daemon.
	ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error)
	// StreamState streams state updates for a run (or all runs if run_id empty).
	StreamState(*StreamStateRequest, grpc.ServerStreamingServer[StateUpdate]) error
	// RespondDecision answers a pending decision request (manual step, failure).
	RespondDecision(context.Context, *RespondDecisionRequest) (*RespondDecisionResponse, error)
	mustEmbedUnimplementedLooperServer()
}

// UnimplementedLooperServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLooperServer struct{}

func (UnimplementedLooperServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedLooperServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedLooperServer) StartLoop(context.Context, *StartLoopRequest) (*StartLoopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartLoop not implemented")
}
func (UnimplementedLooperServer) StopLoop(context.Context, *StopLoopRequest) (*StopLoopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopLoop not implemented")
}
func (UnimplementedLooperServer) ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRuns not implemented")
}
func (UnimplementedLooperServer) StreamState(*StreamStateRequest, grpc.ServerStreamingServer[StateUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamState not implemented")
}
func (UnimplementedLooperServer) RespondDecision(context.Context, *RespondDecisionRequest) (*RespondDecisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RespondDecision not implemented")
}
func (UnimplementedLooperServer) mustEmbedUnimplementedLooperServer() {}
func (UnimplementedLooperServer) testEmbeddedByValue()                {}

// UnsafeLooperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LooperServer will
// result in compilation errors.
type UnsafeLooperServer interface {
	mustEmbedUnimplementedLooperServer()
}

func RegisterLooperServer(s grpc.ServiceRegistrar, srv LooperServer) {
	// If the following call panics, it indicates UnimplementedLooperServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Looper_ServiceDesc, srv)
}

func _Looper_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LooperServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Looper_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LooperServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Looper_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LooperServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Looper_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LooperServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Looper_StartLoop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartLoopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LooperServer).StartLoop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Looper_StartLoop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LooperServer).StartLoop(ctx, req.(*StartLoopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Looper_StopLoop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopLoopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LooperServer).StopLoop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Looper_StopLoop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LooperServer).StopLoop(ctx, req.(*StopLoopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Looper_ListRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LooperServer).ListRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Looper_ListRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LooperServer).ListRuns(ctx, req.(*ListRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Looper_StreamState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamStateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LooperServer).StreamState(m, &grpc.GenericServerStream[StreamStateRequest, StateUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Looper_StreamStateServer = grpc.ServerStreamingServer[StateUpdate]

func _Looper_RespondDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RespondDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LooperServer).RespondDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Looper_RespondDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LooperServer).RespondDecision(ctx, req.(*RespondDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Looper_ServiceDesc is the grpc.ServiceDesc for Looper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Looper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "looper.v1.Looper",
	HandlerType: (*LooperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Looper_Ping_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Looper_Shutdown_Handler,
		},
		{
			MethodName: "StartLoop",
			Handler:    _Looper_StartLoop_Handler,
		},
		{
			MethodName: "StopLoop",
			Handler:    _Looper_StopLoop_Handler,
		},
		{
			MethodName: "ListRuns",
			Handler:    _Looper_ListRuns_Handler,
		},
		{
			MethodName: "RespondDecision",
			Handler:    _Looper_RespondDecision_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamState",
			Handler:       _Looper_StreamState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/looper.proto",
}
