// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: proto/looper.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttachInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AttachInput_Start
	//	*AttachInput_Data
	//	*AttachInput_Resize
	Msg           isAttachInput_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachInput) Reset() {
	*x = AttachInput{}
	mi := &file_proto_looper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachInput) ProtoMessage() {}

func (x *AttachInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_looper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachInput.ProtoReflect.Descriptor instead.
func (*AttachInput) Descriptor() ([]byte, []int) {
	return file_proto_looper_proto_rawDescGZIP(), []int{0}
}

func (x *AttachInput) GetMsg() isAttachInput_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AttachInput) GetStart() *AttachStart {
	if x != nil {
		if x, ok := x.Msg.(*AttachInput_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *AttachInput) GetData() []byte {
	if x != nil {
		if x, ok := x.Msg.(*AttachInput_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *AttachInput) GetResize() *Resize {
	if x != nil {
		if x, ok := x.Msg.(*AttachInput_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isAttachInput_Msg interface {
	isAttachInput_Msg()
}

type AttachInput_Start struct {
	Start *AttachStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"` // MUST be the first message
}

type AttachInput_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"` // stdin bytes
}

type AttachInput_Resize struct {
	Resize *Resize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"` // terminal resize
}

func (*AttachInput_Start) isAttachInput_Msg() {}

func (*AttachInput_Data) isAttachInput_Msg() {}

func (*AttachInput_Resize) isAttachInput_Msg() {}

type AttachStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachStart) Reset() {
	*x = AttachStart{}
	mi := &file_proto_looper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachStart) ProtoMessage() {}

func (x *AttachStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_looper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachStart.ProtoReflect.Descriptor instead.
func (*AttachStart) Descriptor() ([]byte, []int) {
	return file_proto_looper_proto_rawDescGZIP(), []int{1}
}

func (x *AttachStart) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type Resize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resize) Reset() {
	*x = Resize{}
	mi := &file_proto_looper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resize) ProtoMessage() {}

func (x *Resize) ProtoReflect() protoreflect.Message {
	mi := &file_proto_looper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resize.ProtoReflect.Descriptor instead.
func (*Resize) Descriptor() ([]byte, []int) {
	return file_proto_looper_proto_rawDescGZIP(), []int{2}
}

func (x *Resize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Resize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type AttachOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachOutput) Reset() {
	*x = AttachOutput{}
	mi := &file_proto_looper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachOutput) ProtoMessage() {}

func (x *AttachOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_looper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachOutput.ProtoReflect.Descriptor instead.
func (*AttachOutput) Descriptor() ([]byte, []int) {
	return file_proto_looper_proto_rawDescGZIP(), []int{3}
}

func (x *AttachOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_looper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_looper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_looper_proto_rawDescGZIP(), []int{4}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_looper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_looper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_looper_proto_rawDescGZIP(), []int{5}
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_proto_looper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_looper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_proto_looper_proto_rawDescGZIP(), []int{6}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_proto_looper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_looper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_proto_looper_proto_rawDescGZIP(), []int{7}
}

type StartLoopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoopName      string                 `protobuf:"bytes,1,opt,name=loop_name,json=loopName,proto3" json:"loop_name,omitempty"` // resolved under base_dir/loops/<name>.yaml if loop_file empty
	LoopFile      string                 `protobuf:"bytes,2,opt,name=loop_file,json=loopFile,proto3" json:"loop_file,omitempty"` // explicit loop file (overrides loop_name)
	BaseDir       string                 `protobuf:"bytes,3,opt,name=base_dir,json=baseDir,proto3" json:"base_dir,omitempty"`    // the .looper dir
	Workdir       string                 `protobuf:"bytes,4,opt,name=workdir,proto3" json:"workdir,omitempty"`                   // execution dir
	Concurrency   int32                  `protobuf:"varint,5,opt,name=concurrency,proto3" json:"concurrency,omitempty"`          // number of workers; 0 = the loop's configured concurrency
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartLoopRequest) Reset() {
	*x = StartLoopRequest{}
	mi := &file_proto_looper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLoopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLoopRequest) ProtoMessage() {}

func (x *StartLoopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_looper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLoopRequest.ProtoReflect.Descriptor instead.
func (*StartLoopRequest) Descriptor() ([]byte, []int) {
	return file_proto_looper_proto_rawDescGZIP(), []int{8}
}

func (x *StartLoopRequest) GetLoopName() string {
	if x != nil {
		return x.LoopName
	}
	return ""
}

func (x *StartLoopRequest) GetLoopFile() string {
	if x != nil {
		return x.LoopFile
	}
	return ""
}

func (x *StartLoopRequest) GetBaseDir() string {
	if x != nil {
		return x.BaseDir
	}
	return ""
}

func (x *StartLoopRequest) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

func (x *StartLoopRequest) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

type StartLoopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartLoopResponse) Reset() {
	*x = StartLoopResponse{}
	mi := &file_proto_looper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLoopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLoopResponse) ProtoMessage() {}

func (x *StartLoopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_looper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLoopResponse.ProtoReflect.Descriptor instead.
func (*StartLoopResponse) Descriptor() ([]byte, []int) {
	return file_proto_looper_proto_rawDescGZIP(), []int{9}
}

func (x *StartLoopResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type StopLoopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopLoopRequest) Reset() {
	*x = StopLoopRequest{}
	mi := &file_proto_looper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopLoopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopLoopRequest) ProtoMessage() {}

func (x *StopLoopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_looper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopLoopRequest.ProtoReflect.Descriptor instead.
func (*StopLoopRequest) Descriptor() ([]byte, []int) {
	return file_proto_looper_proto_rawDescGZIP(), []int{10}
}

func (x *StopLoopRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type StopLoopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopLoopResponse) Reset() {
	*x = StopLoopResponse{}
	mi := &file_proto_looper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopLoopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopLoopResponse) ProtoMessage() {}

func (x *StopLoopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_looper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopLoopResponse.ProtoReflect.Descriptor instead.
func (*StopLoopResponse) Descriptor() ([]byte, []int) {
	return file_proto_looper_proto_rawDescGZIP(), []int{11}
}

type ListRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsRequest) Reset() {
	*x = ListRunsRequest{}
	mi := &file_proto_looper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsRequest) ProtoMessage() {}

func (x *ListRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_looper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsRequest.ProtoReflect.Descriptor instead.
func (*ListRunsRequest) Descriptor() ([]byte, []int) {
	return file_proto_looper_proto_rawDescGZIP(), []int{12}
}

type WorkerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Task          string                 `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"` // the worker's current work unit (task var)
	Iteration     int32                  `protobuf:"varint,3,opt,name=iteration,proto3" json:"iteration,omitempty"`
	CurrentStep   string                 `protobuf:"bytes,4,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // running | idle | done | stopped | error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	mi := &file_proto_looper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_looper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_proto_looper_proto_rawDescGZIP(), []int{13}
}

func (x *WorkerInfo) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerInfo) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *WorkerInfo) GetIteration() int32 {
	if x != nil {
		return x.Iteration
	}
	return 0
}

func (x *WorkerInfo) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *WorkerInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *WorkerInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RunInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	LoopName      string                 `protobuf:"bytes,2,opt,name=loop_name,json=loopName,proto3" json:"loop_name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // running | done | stopped | error
	Iteration     int32                  `protobuf:"varint,4,opt,name=iteration,proto3" json:"iteration,omitempty"`
	CurrentStep   string                 `protobuf:"bytes,5,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	State         string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	Workers       []*WorkerInfo          `protobuf:"bytes,8,rep,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunInfo) Reset() {
	*x = RunInfo{}
	mi := &file_proto_looper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunInfo) ProtoMessage() {}

func (x *RunInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_looper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunInfo.ProtoReflect.Descriptor instead.
func (*RunInfo) Descriptor() ([]byte, []int) {
	return file_proto_looper_proto_rawDescGZIP(), []int{14}
}

func (x *RunInfo) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunInfo) GetLoopName() string {
	if x != nil {
		return x.LoopName
	}
	return ""
}

func (x *RunInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RunInfo) GetIteration() int32 {
	if x != nil {
		return x.Iteration
	}
	return 0
}

func (x *RunInfo) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *RunInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *RunInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RunInfo) GetWorkers() []*WorkerInfo {
	if x != nil {
		return x.Workers
	}
	return nil
}

type ListRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*RunInfo             `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsResponse) Reset() {
	*x = ListRunsResponse{}
	mi := &file_proto_looper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsResponse) ProtoMessage() {}

func (x *ListRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_looper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsResponse.ProtoReflect.Descriptor instead.
func (*ListRunsResponse) Descriptor() ([]byte, []int) {
	return file_proto_looper_proto_rawDescGZIP(), []int{15}
}

func (x *ListRunsResponse) GetRuns() []*RunInfo {
	if x != nil {
		return x.Runs
	}
	return nil
}

type StreamStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStateRequest) Reset() {
	*x = StreamStateRequest{}
	mi := &file_proto_looper_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStateRequest) ProtoMessage() {}

func (x *StreamStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_looper_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStateRequest.ProtoReflect.Descriptor instead.
func (*StreamStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_looper_proto_rawDescGZIP(), []int{16}
}

func (x *StreamStateRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

// StateUpdate is one event on a run's state stream.
type StateUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"` // step_start | state | decision_request | run_done | log
	LoopName      string                 `protobuf:"bytes,3,opt,name=loop_name,json=loopName,proto3" json:"loop_name,omitempty"`
	Iteration     int32                  `protobuf:"varint,4,opt,name=iteration,proto3" json:"iteration,omitempty"`
	Step          string                 `protobuf:"bytes,5,opt,name=step,proto3" json:"step,omitempty"`
	State         string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,8,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // set when kind == decision_request
	Options       []string               `protobuf:"bytes,9,rep,name=options,proto3" json:"options,omitempty"`                      // e.g. ["advance","retry","abort"]
	WorkerId      string                 `protobuf:"bytes,10,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`   // which worker this update is about
	Task          string                 `protobuf:"bytes,11,opt,name=task,proto3" json:"task,omitempty"`                           // the worker's current work unit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateUpdate) Reset() {
	*x = StateUpdate{}
	mi := &file_proto_looper_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateUpdate) ProtoMessage() {}

func (x *StateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_looper_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateUpdate.ProtoReflect.Descriptor instead.
func (*StateUpdate) Descriptor() ([]byte, []int) {
	return file_proto_looper_proto_rawDescGZIP(), []int{17}
}

func (x *StateUpdate) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StateUpdate) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *StateUpdate) GetLoopName() string {
	if x != nil {
		return x.LoopName
	}
	return ""
}

func (x *StateUpdate) GetIteration() int32 {
	if x != nil {
		return x.Iteration
	}
	return 0
}

func (x *StateUpdate) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *StateUpdate) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *StateUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StateUpdate) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StateUpdate) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *StateUpdate) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *StateUpdate) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

type RespondDecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Outcome       string                 `protobuf:"bytes,3,opt,name=outcome,proto3" json:"outcome,omitempty"` // advance | retry | abort
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondDecisionRequest) Reset() {
	*x = RespondDecisionRequest{}
	mi := &file_proto_looper_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondDecisionRequest) ProtoMessage() {}

func (x *RespondDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_looper_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondDecisionRequest.ProtoReflect.Descriptor instead.
func (*RespondDecisionRequest) Descriptor() ([]byte, []int) {
	return file_proto_looper_proto_rawDescGZIP(), []int{18}
}

func (x *RespondDecisionRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RespondDecisionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RespondDecisionRequest) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

type RespondDecisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondDecisionResponse) Reset() {
	*x = RespondDecisionResponse{}
	mi := &file_proto_looper_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondDecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondDecisionResponse) ProtoMessage() {}

func (x *RespondDecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_looper_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondDecisionResponse.ProtoReflect.Descriptor instead.
func (*RespondDecisionResponse) Descriptor() ([]byte, []int) {
	return file_proto_looper_proto_rawDescGZIP(), []int{19}
}

var File_proto_looper_proto protoreflect.FileDescriptor

const file_proto_looper_proto_rawDesc = "" +
	"\n" +
	"\x12proto/looper.proto\x12\tlooper.v1\"\x87\x01\n" +
	"\vAttachInput\x12.\n" +
	"\x05start\x18\x01 \x01(\v2\x16.looper.v1.AttachStartH\x00R\x05start\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04data\x12+\n" +
	"\x06resize\x18\x03 \x01(\v2\x11.looper.v1.ResizeH\x00R\x06resizeB\x05\n" +
	"\x03msg\"$\n" +
	"\vAttachStart\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"0\n" +
	"\x06Resize\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\"\"\n" +
	"\fAttachOutput\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse\"\xa3\x01\n" +
	"\x10StartLoopRequest\x12\x1b\n" +
	"\tloop_name\x18\x01 \x01(\tR\bloopName\x12\x1b\n" +
	"\tloop_file\x18\x02 \x01(\tR\bloopFile\x12\x19\n" +
	"\bbase_dir\x18\x03 \x01(\tR\abaseDir\x12\x18\n" +
	"\aworkdir\x18\x04 \x01(\tR\aworkdir\x12 \n" +
	"\vconcurrency\x18\x05 \x01(\x05R\vconcurrency\"*\n" +
	"\x11StartLoopResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"(\n" +
	"\x0fStopLoopRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\x12\n" +
	"\x10StopLoopResponse\"\x11\n" +
	"\x0fListRunsRequest\"\xac\x01\n" +
	"\n" +
	"WorkerInfo\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x12\n" +
	"\x04task\x18\x02 \x01(\tR\x04task\x12\x1c\n" +
	"\titeration\x18\x03 \x01(\x05R\titeration\x12!\n" +
	"\fcurrent_step\x18\x04 \x01(\tR\vcurrentStep\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\xf3\x01\n" +
	"\aRunInfo\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n" +
	"\tloop_name\x18\x02 \x01(\tR\bloopName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1c\n" +
	"\titeration\x18\x04 \x01(\x05R\titeration\x12!\n" +
	"\fcurrent_step\x18\x05 \x01(\tR\vcurrentStep\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12/\n" +
	"\aworkers\x18\b \x03(\v2\x15.looper.v1.WorkerInfoR\aworkers\":\n" +
	"\x10ListRunsResponse\x12&\n" +
	"\x04runs\x18\x01 \x03(\v2\x12.looper.v1.RunInfoR\x04runs\"+\n" +
	"\x12StreamStateRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\xa1\x02\n" +
	"\vStateUpdate\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1b\n" +
	"\tloop_name\x18\x03 \x01(\tR\bloopName\x12\x1c\n" +
	"\titeration\x18\x04 \x01(\x05R\titeration\x12\x12\n" +
	"\x04step\x18\x05 \x01(\tR\x04step\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\b \x01(\tR\trequestId\x12\x18\n" +
	"\aoptions\x18\t \x03(\tR\aoptions\x12\x1b\n" +
	"\tworker_id\x18\n" +
	" \x01(\tR\bworkerId\x12\x12\n" +
	"\x04task\x18\v \x01(\tR\x04task\"h\n" +
	"\x16RespondDecisionRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x18\n" +
	"\aoutcome\x18\x03 \x01(\tR\aoutcome\"\x19\n" +
	"\x17RespondDecisionResponse2\xb9\x04\n" +
	"\x06Looper\x127\n" +
	"\x04Ping\x12\x16.looper.v1.PingRequest\x1a\x17.looper.v1.PingResponse\x12C\n" +
	"\bShutdown\x12\x1a.looper.v1.ShutdownRequest\x1a\x1b.looper.v1.ShutdownResponse\x12F\n" +
	"\tStartLoop\x12\x1b.looper.v1.StartLoopRequest\x1a\x1c.looper.v1.StartLoopResponse\x12C\n" +
	"\bStopLoop\x12\x1a.looper.v1.StopLoopRequest\x1a\x1b.looper.v1.StopLoopResponse\x12C\n" +
	"\bListRuns\x12\x1a.looper.v1.ListRunsRequest\x1a\x1b.looper.v1.ListRunsResponse\x12F\n" +
	"\vStreamState\x12\x1d.looper.v1.StreamStateRequest\x1a\x16.looper.v1.StateUpdate0\x01\x12X\n" +
	"\x0fRespondDecision\x12!.looper.v1.RespondDecisionRequest\x1a\".looper.v1.RespondDecisionResponse\x12=\n" +
	"\x06Attach\x12\x16.looper.v1.AttachInput\x1a\x17.looper.v1.AttachOutput(\x010\x01B%Z#github.com/jbofill10/looper/rpc;rpcb\x06proto3"

var (
	file_proto_looper_proto_rawDescOnce sync.Once
	file_proto_looper_proto_rawDescData []byte
)

func file_proto_looper_proto_rawDescGZIP() []byte {
	file_proto_looper_proto_rawDescOnce.Do(func() {
		file_proto_looper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_looper_proto_rawDesc), len(file_proto_looper_proto_rawDesc)))
	})
	return file_proto_looper_proto_rawDescData
}

var file_proto_looper_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_looper_proto_goTypes = []any{
	(*AttachInput)(nil),             // 0: looper.v1.AttachInput
	(*AttachStart)(nil),             // 1: looper.v1.AttachStart
	(*Resize)(nil),                  // 2: looper.v1.Resize
	(*AttachOutput)(nil),            // 3: looper.v1.AttachOutput
	(*PingRequest)(nil),             // 4: looper.v1.PingRequest
	(*PingResponse)(nil),            // 5: looper.v1.PingResponse
	(*ShutdownRequest)(nil),         // 6: looper.v1.ShutdownRequest
	(*ShutdownResponse)(nil),        // 7: looper.v1.ShutdownResponse
	(*StartLoopRequest)(nil),        // 8: looper.v1.StartLoopRequest
	(*StartLoopResponse)(nil),       // 9: looper.v1.StartLoopResponse
	(*StopLoopRequest)(nil),         // 10: looper.v1.StopLoopRequest
	(*StopLoopResponse)(nil),        // 11: looper.v1.StopLoopResponse
	(*ListRunsRequest)(nil),         // 12: looper.v1.ListRunsRequest
	(*WorkerInfo)(nil),              // 13: looper.v1.WorkerInfo
	(*RunInfo)(nil),                 // 14: looper.v1.RunInfo
	(*ListRunsResponse)(nil),        // 15: looper.v1.ListRunsResponse
	(*StreamStateRequest)(nil),      // 16: looper.v1.StreamStateRequest
	(*StateUpdate)(nil),             // 17: looper.v1.StateUpdate
	(*RespondDecisionRequest)(nil),  // 18: looper.v1.RespondDecisionRequest
	(*RespondDecisionResponse)(nil), // 19: looper.v1.RespondDecisionResponse
}
var file_proto_looper_proto_depIdxs = []int32{
	1,  // 0: looper.v1.AttachInput.start:type_name -> looper.v1.AttachStart
	2,  // 1: looper.v1.AttachInput.resize:type_name -> looper.v1.Resize
	13, // 2: looper.v1.RunInfo.workers:type_name -> looper.v1.WorkerInfo
	14, // 3: looper.v1.ListRunsResponse.runs:type_name -> looper.v1.RunInfo
	4,  // 4: looper.v1.Looper.Ping:input_type -> looper.v1.PingRequest
	6,  // 5: looper.v1.Looper.Shutdown:input_type -> looper.v1.ShutdownRequest
	8,  // 6: looper.v1.Looper.StartLoop:input_type -> looper.v1.StartLoopRequest
	10, // 7: looper.v1.Looper.StopLoop:input_type -> looper.v1.StopLoopRequest
	12, // 8: looper.v1.Looper.ListRuns:input_type -> looper.v1.ListRunsRequest
	16, // 9: looper.v1.Looper.StreamState:input_type -> looper.v1.StreamStateRequest
	18, // 10: looper.v1.Looper.RespondDecision:input_type -> looper.v1.RespondDecisionRequest
	0,  // 11: looper.v1.Looper.Attach:input_type -> looper.v1.AttachInput
	5,  // 12: looper.v1.Looper.Ping:output_type -> looper.v1.PingResponse
	7,  // 13: looper.v1.Looper.Shutdown:output_type -> looper.v1.ShutdownResponse
	9,  // 14: looper.v1.Looper.StartLoop:output_type -> looper.v1.StartLoopResponse
	11, // 15: looper.v1.Looper.StopLoop:output_type -> looper.v1.StopLoopResponse
	15, // 16: looper.v1.Looper.ListRuns:output_type -> looper.v1.ListRunsResponse
	17, // 17: looper.v1.Looper.StreamState:output_type -> looper.v1.StateUpdate
	19, // 18: looper.v1.Looper.RespondDecision:output_type -> looper.v1.RespondDecisionResponse
	3,  // 19: looper.v1.Looper.Attach:output_type -> looper.v1.AttachOutput
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_looper_proto_init() }
func file_proto_looper_proto_init() {
	if File_proto_looper_proto != nil {
		return
	}
	file_proto_looper_proto_msgTypes[0].OneofWrappers = []any{
		(*AttachInput_Start)(nil),
		(*AttachInput_Data)(nil),
		(*AttachInput_Resize)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_looper_proto_rawDesc), len(file_proto_looper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_looper_proto_goTypes,
		DependencyIndexes: file_proto_looper_proto_depIdxs,
		MessageInfos:      file_proto_looper_proto_msgTypes,
	}.Build()
	File_proto_looper_proto = out.File
	file_proto_looper_proto_goTypes = nil
	file_proto_looper_proto_depIdxs = nil
}
